language: node_js
node_js: 
    - 12.6.0
sudo: required
cache:
    apt: true
    directories:
        - node_modules
install:
    - npm install
    - npm install hexo-deployer-git --save 
before_install:
    - npm install -g hexo-cli
after_script:
    - git config user.name "liupzmin"
    - git config user.email "676333678@qq.com"
    - sed -i "s/gh_token/${access_token}/g" ./_config.yml
    - hexo deploy
script:
    - hexo clean
    - hexo g
branches:
    only:
        - hexo_resource
