# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 巴流的博客
subtitle: 一只兔子的幸福生活
description: 左手人文 | 右手科技
keywords:
author: 巴流
language: zh-CN
timezone: Asia/Shanghai


archive_generator:
  per_page: 100
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 100

tag_generator:
  per_page: 100
  enable_index_page: false
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://liupzmin.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  # For disable links in code blocks.
  autolink: false

kramed:
  # For preserve original quotes in code blocks.
  smartypants: false



#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:

  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  cache:
    enable: true

  custom_file_path:
    style: source/_data/styles.styl


  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  seo: true
  index_with_subtitle: true
  exturl: true


  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini


  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2014
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: NexT
    # -------------------------------------------------------------
    powered:
      enable: true
      version: true
    theme:
      enable: true
      version: true

  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: false

  github_banner:
    enable: true
    permalink: https://github.com/liupzmin 
    title: Follow me on GitHub


  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    home: / || home
    archives: /archives/ || archive
    tags: /tags/ || tags
    categories: /categories/ || th
    about: /about/ || user
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  menu_settings:
    icons: true
    badges: true


  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  avatar:
    url: /images/gzh.jpg
    rounded: false
    rotated: false

  social:
    GitHub: https://github.com/liupzmin || github
    E-Mail: mailto:liupzmin@gmail.com || envelope


  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true

  sidebar:
    onmobile: true

  back2top:
    enable: true
    sidebar: false
    scrollpercent: true


  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 4
    wpm: 275

  post_edit:
    enable: true
    url: https://github.com/liupzmin/liupzmin.github.io/edit/hexo_resource/source/


  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true


  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #


  # ============================================================= #
  # ----------------- Statistics and Analytics ------------------ #
  # ============================================================= #

  yandex_site_verification: 3ac9ae36ddebb425


  # ============================================================= #
  # ---------------------- Search Services ---------------------- #
  # ============================================================= #

  search:
    path: search.xml
    field: post
    format: html
    limit: 10000

  # ============================================================= #
  # -------------------- External Libraries --------------------- #
  # ============================================================= #

  motion:
    enable: false
    async: true
    transition:
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideUpIn

  lazyload: true
  
  fancybox: true


  # ============================================================= #
  # ---------------------- Math Equations ----------------------- #
  # ============================================================= #

  math:
    enable: true
    per_page: true
    engine: mathjax
    mathjax:
      cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML


  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    border_radius: 0
    light_bg_offset: -3

  tabs:
    enable: true
    transition:
      tabs: true
      labels: true
    border_radius: 0

  gitalk:
    enable: true
    ClientID: ae0756501dfc5de89d35
    ClientSecret: 26befb359f7a466031bb96b4b7e0715c41c63fb8 
    repo: liupzmin.github.io
    owner: liupzmin
    adminUser: "['liupzmin']"
    labels: "['Gitalk']"
    perPage: 15
    pagerDirection: last
    createIssueManually: true
    distractionFreeMode: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gh_token@github.com/liupzmin/liupzmin.github.io.git
  branch: master
