name: CI

on:
 push:
    branches:
    - hexo_resource

jobs:
 build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
            node-version: 16
    - name: Setup Hexo env
      env:
         ACTION_DEPLOY_KEY: ${{secrets.ACTION_DEPLOY_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "liupzmin"
        git config --global user.email "676333678@qq.com"
        npm install hexo-cli -g
        npm install hexo-util --save
        npm install js-yaml --save
        npm install
        
    - name: deploy to github
      run: |
         hexo clean && hexo generate && hexo deploy
